import { PurchaseRecord, User, Catalog, AuditLogEntry, AppNotification } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    username: 'admin',
    nombreCompleto: 'Lic. Kevin Gerarado López de León',
    email: 'klopez@oj.gob.gt',
    password: 'Guate2026*',
    rol: 'administrador',
    cargo: 'Gerente de Informática y Telecomunicaciones',
    departamento: 'Gerencia de Informática - OJ',
    activo: true,
    fechaCreacion: '2024-01-10T08:00:00Z',
    ultimoAcceso: '2026-09-03T14:15:00Z',
  },
  {
    id: 'usr-auditor-1',
    username: 'auditor',
    nombreCompleto: 'Licda. Patricia Morales Estrada',
    email: 'pmorales@oj.gob.gt',
    password: 'audit',
    rol: 'auditor',
    cargo: 'Auditora Gubernamental Senior',
    departamento: 'Dirección de Auditoría Interna - OJ',
    activo: true,
    fechaCreacion: '2024-02-01T09:30:00Z',
    ultimoAcceso: '2026-09-03T11:20:00Z',
  },
  {
    id: 'usr-operador-1',
    username: 'operador',
    nombreCompleto: 'Ing. Mario Roberto Gómez Salazar',
    email: 'mgomez@oj.gob.gt',
    password: 'user123',
    rol: 'usuario_estandar',
    cargo: 'Analista de Compras de Tecnología',
    departamento: 'Unidad de Gestión de Adquisiciones GIT',
    activo: true,
    fechaCreacion: '2024-03-15T10:00:00Z',
    ultimoAcceso: '2026-09-03T13:45:00Z',
  },
  {
    id: 'usr-operador-2',
    username: 'jfuentes',
    nombreCompleto: 'Lic. Jorge Fuentes Alvarado',
    email: 'jfuentes@oj.gob.gt',
    password: 'user123',
    rol: 'usuario_estandar',
    cargo: 'Especialista en Infraestructura Informática',
    departamento: 'Subgerencia de Redes y Telecomunicaciones',
    activo: true,
    fechaCreacion: '2024-04-10T08:30:00Z',
    ultimoAcceso: '2026-09-02T16:10:00Z',
  }
];

export const INITIAL_CATALOGS: Catalog[] = [
  {
    id: 'cat-estatus',
    codigo: 'ESTATUS_EVENTO',
    nombre: 'Estatus del Evento',
    descripcion: 'Estados oficiales de los eventos de adquisiciones según normativa Guatecompras y GIT',
    esSistema: true,
    items: [
      { id: 'est-1', codigo: 'EVALUACION', valor: 'Evaluación', descripcion: 'En proceso de calificación técnica y financiera por la comisión', activo: true, color: 'blue' },
      { id: 'est-2', codigo: 'ADJUDICACION', valor: 'Adjudicación', descripcion: 'Evento resuelto favorablemente a proveedor adjudicado', activo: true, color: 'emerald' },
      { id: 'est-3', codigo: 'PRESCINDIDO', valor: 'Prescindido', descripcion: 'Evento dejado sin efecto por razones de interés institucional', activo: true, color: 'amber' },
      { id: 'est-4', codigo: 'DESIERTO', valor: 'Desierto', descripcion: 'Ninguna oferta cumplió con los requerimientos técnicos o no hubo postores', activo: true, color: 'rose' },
    ]
  },
  {
    id: 'cat-evaluado-git',
    codigo: 'EVALUADO_GIT',
    nombre: 'Evaluado por la GIT',
    descripcion: 'Dictamen técnico y validación por la Gerencia de Informática y Telecomunicaciones',
    esSistema: true,
    items: [
      { id: 'git-1', codigo: 'SI', valor: 'Sí', descripcion: 'Cuenta con dictamen técnico favorable de la GIT', activo: true, color: 'emerald' },
      { id: 'git-2', codigo: 'NO', valor: 'No', descripcion: 'Sin dictamen técnico o pendiente de emitir', activo: true, color: 'slate' },
    ]
  },
  {
    id: 'cat-areas',
    codigo: 'AREA_SOLICITANTE',
    nombre: 'Área Solicitante',
    descripcion: 'Áreas y unidades técnicas de la Gerencia de Informática y del Organismo Judicial',
    esSistema: false,
    items: [
      { id: 'area-1', codigo: 'SOPORTE_TECNICO', valor: 'Soporte técnico', descripcion: 'Atención presencial a usuarios y juzgados', activo: true, color: 'teal' },
      { id: 'area-2', codigo: 'SOPORTE_REMOTO', valor: 'Soporte Técnico Remoto', descripcion: 'Mesa de ayuda y soporte a distancia', activo: true, color: 'cyan' },
      { id: 'area-3', codigo: 'VIDEOAUDIENCIAS', valor: 'Sección de Videoaudiencias', descripcion: 'Salas de audiencias y videoconferencias judiciales', activo: true, color: 'violet' },
      { id: 'area-4', codigo: 'REDES_TELECOM', valor: 'Redes y Telecomunicaciones', descripcion: 'Infraestructura de red, fibra óptica y telefonía', activo: true, color: 'blue' },
      { id: 'area-5', codigo: 'DESARROLLO_SISTEMAS', valor: 'Desarrollo y Administración de Sistemas', descripcion: 'Ingeniería de software, bases de datos y desarrollo', activo: true, color: 'indigo' },
      { id: 'area-6', codigo: 'DEPTO_SERVICIOS_INF', valor: 'Departamento de Servicios Informáticos', descripcion: 'Gestión central de servicios y operaciones TI', activo: true, color: 'amber' },
      { id: 'area-7', codigo: 'SEGURIDAD_INF', valor: 'Seguridad Informática', descripcion: 'Ciberseguridad, auditoría de sistemas y perímetros', activo: true, color: 'rose' },
    ]
  },
  {
    id: 'cat-categorias',
    codigo: 'CATEGORIA_TECNOLOGICA',
    nombre: 'Categoría Tecnológica',
    descripcion: 'Clasificación de bienes y servicios informáticos del Organismo Judicial',
    esSistema: false,
    items: [
      { id: 'catg-1', codigo: 'SERV_ALM', valor: 'Servidores y Almacenamiento', descripcion: 'Centros de datos, clusters SAN/NAS y blades', activo: true, color: 'indigo' },
      { id: 'catg-2', codigo: 'RED_TELECOM', valor: 'Redes y Telecomunicaciones', descripcion: 'Switches, routers, fibra óptica y enlaces dedicados', activo: true, color: 'cyan' },
      { id: 'catg-3', codigo: 'CIBERSEG', valor: 'Ciberseguridad y Perímetro', descripcion: 'Firewalls, EDR, SIEM y análisis de vulnerabilidades', activo: true, color: 'purple' },
      { id: 'catg-4', codigo: 'EQUIPO_JUZGADOS', valor: 'Estaciones de Trabajo y Periféricos', descripcion: 'PCs, laptops, impresoras para juzgados y tribunales', activo: true, color: 'teal' },
      { id: 'catg-5', codigo: 'LIC_SOFT', valor: 'Licenciamiento y Software Judicial', descripcion: 'Sistemas operativos, bases de datos y software especializado', activo: true, color: 'blue' },
      { id: 'catg-6', codigo: 'AUDIO_VIDEO', valor: 'Audio/Video para Salas de Audiencias', descripcion: 'Sistemas de grabación digital y microfonía estenográfica', activo: true, color: 'violet' },
    ]
  },
  {
    id: 'cat-dependencias',
    codigo: 'DEPENDENCIA_SOLICITANTE',
    nombre: 'Dependencias Solicitantes',
    descripcion: 'Unidades y juzgados que requieren adquisiciones tecnológicas',
    esSistema: false,
    items: [
      { id: 'dep-1', codigo: 'GIT_INFRA', valor: 'Subgerencia de Infraestructura GIT', activo: true },
      { id: 'dep-2', codigo: 'GIT_DESARROLLO', valor: 'Subgerencia de Desarrollo de Sistemas GIT', activo: true },
      { id: 'dep-3', codigo: 'GIT_SEGURIDAD', valor: 'Unidad de Seguridad de la Información', activo: true },
      { id: 'dep-4', codigo: 'GIT_SOPORTE', valor: 'Unidad de Soporte Técnico Departamental', activo: true },
      { id: 'dep-5', codigo: 'SALA_VISTAS', valor: 'Salas de Vistas y Tribunales Penales', activo: true },
      { id: 'dep-6', codigo: 'CENTRO_DATOS', valor: 'Centro de Cómputo Principal Torre de Tribunales', activo: true },
    ]
  },
  {
    id: 'cat-modalidades',
    codigo: 'MODALIDAD_COMPRA',
    nombre: 'Modalidad de Compra',
    descripcion: 'Modalidades de contratación pública según Ley de Contrataciones del Estado',
    esSistema: false,
    items: [
      { id: 'mod-1', codigo: 'COMPRA_DIRECTA', valor: 'Compra Directa', descripcion: 'Montos menores a Q.90,000.00', activo: true },
      { id: 'mod-2', codigo: 'COTIZACION', valor: 'Cotización Pública', descripcion: 'Montos entre Q.90,000.01 y Q.900,000.00', activo: true },
      { id: 'mod-3', codigo: 'LICITACION', valor: 'Licitación Pública', descripcion: 'Montos mayores a Q.900,000.00', activo: true },
      { id: 'mod-4', codigo: 'CONTRATO_ABIERTO', valor: 'Contrato Abierto', descripcion: 'Convenio marco con precios fijados por Minfin', activo: true },
    ]
  }
];

export const INITIAL_PURCHASES: PurchaseRecord[] = [
  {
    id: 'pur-2026-001',
    descripcion: 'Adquisición de servidores en rack de alta disponibilidad para el Sistema de Gestión de Tribunales (SGT) en el Data Center Central.',
    f56e: '000001-2026',
    f56: '000001',
    f56Documento: {
      nombre: 'F56_Oficial_Servidores_SGT_000001.pdf',
      tamano: 245760,
      tipo: 'application/pdf',
      fechaSubida: '2026-01-16T11:20:00Z',
      dataUrl: 'data:application/pdf;base64,JVBERi0xLjQKJcTl8uXrp/Og0MTGCjEgMCBvYmoKPDwKL1R5cGUgL0NhdGFsb2cKL1BhZ2VzIDIgMCBSCj4+CmVuZG9iagoyIDAgb2JqCjw8Ci9UeXBlIC9QYWdlcwovS2lkcyBbMyAwIFJdCi9Db3VudCAxCj4+CmVuZG9iagozIDAgb2JqCjw8Ci9UeXBlIC9QYWdlCi9QYXJlbnQgMiAwIFIKL01lZGlhQm94IFswIDAgNjEyIDc5Ml0KL0NvbnRlbnRzIDQgMCBSCj4+CmVuZG9iago0IDAgb2JqCjw8Ci9MZW5ndGggNzgKPj4Kc3RyZWFtCkJUCi9GMSAxMiBUZgoxMDAgNzAwIFRkCihGb3JtdWxhcmlvIEY1NiBPZmljaWFsIC0gT3JnYW5pc21vIEp1ZGljaWFsIGRlIEd1YXRlbWFsYSkgVGoKRVQKZW5kc3RyZWFtCmVuZG9iagp4cmVmCjAgNQowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMTUgMDAwMDAgbiAKMDAwMDAwMDA2OCAwMDAwMCBuIAowMDAwMDAwMTI1IDAwMDAwIG4gCjAwMDAwMDAyMjEgMDAwMDAgbiAKdHJhaWxlcgo8PAovU2l6ZSA1Ci9Sb290IDEgMCBSCj4+CnN0YXJ0eHJlZgoxMzU2CiUlRU9G'
    },
    fechaSolicitud: '2026-01-15',
    fechaVoBo: '2026-01-22',
    fechaAutorizado: '2026-01-29',
    nog: '21948201',
    fechaPublicacion: '2026-02-05',
    fechaOfertas: '2026-02-28',
    cantidadOfertas: 4,
    monto: 845000.00,
    evaluadoGIT: 'Sí',
    fechaDictamenGIT: '2026-02-18',
    estatusEvento: 'Adjudicación',
    areaSolicitante: 'Departamento de Servicios Informáticos',
    categoriaTecnologica: 'Servidores y Almacenamiento',
    dependenciaSolicitante: 'Centro de Cómputo Principal Torre de Tribunales',
    modalidadCompra: 'Cotización Pública',
    proveedorAdjudicado: 'Tecnologías y Sistemas Corporativos, S.A.',
    creadoPor: 'Lic. Kevin Gerarado López de León',
    fechaCreacion: '2026-01-15T09:00:00Z',
    observaciones: 'Adjudicado a proveedor con mayor puntaje técnico. Garantía de 3 años On-Site 24x7.'
  },
  {
    id: 'pur-2026-002',
    descripcion: 'Renovación de licenciamiento anual de motor de bases de datos Enterprise y soporte técnico especializado para registros judiciales.',
    f56e: '000012-2026',
    f56: '000012',
    f56Documento: {
      nombre: 'Dictamen_F56_Licenciamiento_000012.pdf',
      tamano: 189440,
      tipo: 'application/pdf',
      fechaSubida: '2026-02-02T14:10:00Z',
      dataUrl: 'data:application/pdf;base64,JVBERi0xLjQKJcTl8uXrp/Og0MTGCjEgMCBvYmoKPDwKL1R5cGUgL0NhdGFsb2cKL1BhZ2VzIDIgMCBSCj4+CmVuZG9iagoyIDAgb2JqCjw8Ci9UeXBlIC9QYWdlcwovS2lkcyBbMyAwIFJdCi9Db3VudCAxCj4+CmVuZG9iago0IDAgb2JqCjw8Ci9MZW5ndGggNzYKPj4Kc3RyZWFtCkJUCi9GMSAxMiBUZgoxMDAgNzAwIFRkCihGb3JtdWxhcmlvIEY1NiAtIExpY2VuY2lhbWllbnRvIEJhc2VzIGRlIERhdG9zIE9KKSBUagpFVAplbmRzdHJlYW0KZW5kb2Jq'
    },
    fechaSolicitud: '2026-02-01',
    fechaVoBo: '2026-02-08',
    fechaAutorizado: '2026-02-14',
    nog: '22019482',
    fechaPublicacion: '2026-02-20',
    fechaOfertas: '2026-03-12',
    cantidadOfertas: 2,
    monto: 1250000.00,
    evaluadoGIT: 'Sí',
    fechaDictamenGIT: '2026-02-25',
    estatusEvento: 'Evaluación',
    areaSolicitante: 'Desarrollo y Administración de Sistemas',
    categoriaTecnologica: 'Licenciamiento y Software Judicial',
    dependenciaSolicitante: 'Subgerencia de Desarrollo de Sistemas GIT',
    modalidadCompra: 'Licitación Pública',
    creadoPor: 'Mario Gómez',
    fechaCreacion: '2026-02-01T10:15:00Z',
    observaciones: 'En revisión de ofertas técnicas y cumplimiento de SLAs solicitados.'
  },
  {
    id: 'pur-2026-003',
    descripcion: 'Suministro e instalación de 150 estaciones de trabajo y periféricos para Juzgados de Primera Instancia Penal departamentales.',
    f56e: '000025-2026',
    f56: '000025',
    fechaSolicitud: '2026-01-20',
    fechaVoBo: '2026-01-28',
    fechaAutorizado: '2026-02-04',
    nog: '21837492',
    fechaPublicacion: '2026-02-10',
    fechaOfertas: '2026-03-02',
    cantidadOfertas: 5,
    monto: 690000.00,
    evaluadoGIT: 'Sí',
    fechaDictamenGIT: '2026-02-15',
    estatusEvento: 'Adjudicación',
    areaSolicitante: 'Soporte técnico',
    categoriaTecnologica: 'Estaciones de Trabajo y Periféricos',
    dependenciaSolicitante: 'Unidad de Soporte Técnico Departamental',
    modalidadCompra: 'Cotización Pública',
    proveedorAdjudicado: 'Soluciones Informáticas de Guatemala, S.A.',
    creadoPor: 'Jorge Fuentes',
    fechaCreacion: '2026-01-20T11:30:00Z',
    observaciones: 'Equipo con procesadores i7, 16GB RAM y discos NVMe de 512GB con sello OJ.'
  },
  {
    id: 'pur-2026-004',
    descripcion: 'Mantenimiento preventivo y correctivo de la red de fibra óptica interinstitucional de los Complejos Judiciales Metropolitanos.',
    f56e: '000038-2026',
    f56: '000038',
    fechaSolicitud: '2026-02-10',
    fechaVoBo: '2026-02-17',
    fechaAutorizado: '2026-02-23',
    nog: '22194837',
    fechaPublicacion: '2026-03-01',
    fechaOfertas: '2026-03-20',
    cantidadOfertas: 0,
    monto: 240000.00,
    evaluadoGIT: 'Sí',
    fechaDictamenGIT: '2026-02-22',
    estatusEvento: 'Evaluación',
    areaSolicitante: 'Redes y Telecomunicaciones',
    categoriaTecnologica: 'Redes y Telecomunicaciones',
    dependenciaSolicitante: 'Subgerencia de Infraestructura GIT',
    modalidadCompra: 'Cotización Pública',
    creadoPor: 'Lic. Kevin Gerarado López de León',
    fechaCreacion: '2026-02-10T14:20:00Z',
    observaciones: 'Publicado en Guatecompras. Convocatoria vigente para recepción de plicas.'
  },
  {
    id: 'pur-2026-005',
    descripcion: 'Implementación de sistema perimetral Firewall Next-Gen y módulo de prevención de intrusiones para protección de expedientes judiciales.',
    f56e: '000044-2026',
    f56: '000044',
    f56Documento: {
      nombre: 'F56_Aprobada_Firewall_Perimetral_000044.pdf',
      tamano: 312000,
      tipo: 'application/pdf',
      fechaSubida: '2026-01-11T09:00:00Z',
      dataUrl: 'data:application/pdf;base64,JVBERi0xLjQKJcTl8uXrp/Og0MTGCjEgMCBvYmoKPDwKL1R5cGUgL0NhdGFsb2cKL1BhZ2VzIDIgMCBSCj4+CmVuZG9iago0IDAgb2JqCjw8Ci9MZW5ndGggNzYKPj4Kc3RyZWFtCkJUCi9GMSAxMiBUZgoxMDAgNzAwIFRkCihGb3JtdWxhcmlvIEY1NiAtIFNlZ3VyaWRhZCBQZXJpbWV0cmFsIEZpcmV3YWxsKSBUagpFVAplbmRzdHJlYW0KZW5kb2Jq'
    },
    fechaSolicitud: '2026-01-10',
    fechaVoBo: '2026-01-18',
    fechaAutorizado: '2026-01-25',
    nog: '21748291',
    fechaPublicacion: '2026-02-02',
    fechaOfertas: '2026-02-24',
    cantidadOfertas: 3,
    monto: 480000.00,
    evaluadoGIT: 'Sí',
    fechaDictamenGIT: '2026-01-28',
    estatusEvento: 'Adjudicación',
    areaSolicitante: 'Seguridad Informática',
    categoriaTecnologica: 'Ciberseguridad y Perímetro',
    dependenciaSolicitante: 'Unidad de Seguridad de la Información',
    modalidadCompra: 'Cotización Pública',
    proveedorAdjudicado: 'CyberSec Solutions Centroamérica, S.A.',
    creadoPor: 'Mario Gómez',
    fechaCreacion: '2026-01-10T09:45:00Z',
    observaciones: 'Adjudicación aprobada por el Comité Técnico de Adquisiciones.'
  },
  {
    id: 'pur-2026-006',
    descripcion: 'Equipamiento y modernización de audio, video y estenografía digital para 8 Salas de Vistas y Juicios Orales de Mayor Riesgo.',
    f56e: '000051-2026',
    f56: '000051',
    fechaSolicitud: '2026-01-05',
    fechaVoBo: '2026-01-12',
    fechaAutorizado: '2026-01-18',
    nog: '21682910',
    fechaPublicacion: '2026-01-25',
    fechaOfertas: '2026-02-15',
    cantidadOfertas: 1,
    monto: 395000.00,
    evaluadoGIT: 'No',
    fechaDictamenGIT: '',
    estatusEvento: 'Desierto',
    areaSolicitante: 'Sección de Videoaudiencias',
    categoriaTecnologica: 'Audio/Video para Salas de Audiencias',
    dependenciaSolicitante: 'Salas de Vistas y Tribunales Penales',
    modalidadCompra: 'Cotización Pública',
    creadoPor: 'Jorge Fuentes',
    fechaCreacion: '2026-01-05T08:30:00Z',
    observaciones: 'El único oferente no presentó la solvencia fiscal SAT ni la constancia de colegiado activo requerida.'
  },
  {
    id: 'pur-2026-007',
    descripcion: 'Contratación de servicio de conectividad satelital y backup de contingencia para juzgados de paz en municipios sin cobertura de fibra.',
    f56e: '000063-2026',
    f56: '000063',
    fechaSolicitud: '2026-01-08',
    fechaVoBo: '2026-01-16',
    fechaAutorizado: '2026-01-22',
    nog: '21593820',
    fechaPublicacion: '2026-01-30',
    fechaOfertas: '2026-02-18',
    cantidadOfertas: 2,
    monto: 180000.00,
    evaluadoGIT: 'Sí',
    fechaDictamenGIT: '2026-01-18',
    estatusEvento: 'Prescindido',
    areaSolicitante: 'Redes y Telecomunicaciones',
    categoriaTecnologica: 'Redes y Telecomunicaciones',
    dependenciaSolicitante: 'Subgerencia de Infraestructura GIT',
    modalidadCompra: 'Cotización Pública',
    creadoPor: 'Lic. Kevin Gerarado López de León',
    fechaCreacion: '2026-01-08T10:00:00Z',
    observaciones: 'Se prescindió debido a reestructuración de fondos hacia proyecto de fibra óptica departamental.'
  },
  {
    id: 'pur-2026-008',
    descripcion: 'Adquisición de licencias de firma electrónica avanzada y estampas de tiempo digitales para notificaciones judiciales en línea.',
    f56e: '000072-2026',
    f56: '000072',
    fechaSolicitud: '2026-02-15',
    fechaVoBo: '2026-02-22',
    fechaAutorizado: '2026-03-01',
    nog: '22384910',
    fechaPublicacion: '2026-03-05',
    fechaOfertas: '2026-03-25',
    cantidadOfertas: 3,
    monto: 310000.00,
    evaluadoGIT: 'Sí',
    fechaDictamenGIT: '2026-02-28',
    estatusEvento: 'Evaluación',
    areaSolicitante: 'Desarrollo y Administración de Sistemas',
    categoriaTecnologica: 'Licenciamiento y Software Judicial',
    dependenciaSolicitante: 'Subgerencia de Desarrollo de Sistemas GIT',
    modalidadCompra: 'Cotización Pública',
    creadoPor: 'Mario Gómez',
    fechaCreacion: '2026-02-15T15:00:00Z',
    observaciones: 'Cumpliendo requerimientos del Registro de Prestadores de Servicios de Certificación.'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud-101',
    fecha: '2026-09-03T14:15:22Z',
    usuario: 'admin (Lic. Kevin Gerarado López de León)',
    rol: 'administrador',
    accion: 'LOGIN',
    modulo: 'Autenticación',
    detalles: 'Inicio de sesión exitoso al Sistema de Control de Compras GIT.',
    ip: '10.150.2.45'
  },
  {
    id: 'aud-102',
    fecha: '2026-09-03T13:48:10Z',
    usuario: 'operador (Ing. Mario Gómez)',
    rol: 'usuario_estandar',
    accion: 'CREAR_COMPRA',
    modulo: 'Compras',
    detalles: 'Registro de nuevo evento de compra NOG: 22384910 - Licencias Firma Electrónica por Q.310,000.00',
    registroId: 'pur-2026-008',
    ip: '10.150.2.88'
  },
  {
    id: 'aud-103',
    fecha: '2026-09-03T11:22:05Z',
    usuario: 'auditor (Licda. Patricia Morales)',
    rol: 'auditor',
    accion: 'EXPORTAR_DATOS',
    modulo: 'Auditoría',
    detalles: 'Exportación de reporte consolidado de adquisiciones GIT período 2026.',
    ip: '10.150.1.12'
  },
  {
    id: 'aud-104',
    fecha: '2026-09-02T16:15:00Z',
    usuario: 'admin (Lic. Kevin Gerarado López de León)',
    rol: 'administrador',
    accion: 'CAMBIO_ESTATUS',
    modulo: 'Compras',
    detalles: 'Actualización de estatus a "Adjudicación" para el NOG: 21948201 (Servidores Data Center)',
    registroId: 'pur-2026-001',
    ip: '10.150.2.45',
    valoresAnteriores: { estatusEvento: 'Evaluación' },
    valoresNuevos: { estatusEvento: 'Adjudicación', proveedor: 'Tecnologías y Sistemas Corporativos, S.A.' }
  },
  {
    id: 'aud-105',
    fecha: '2026-09-01T09:10:00Z',
    usuario: 'admin (Lic. Kevin Gerarado López de León)',
    rol: 'administrador',
    accion: 'CREAR_CATALOGO',
    modulo: 'Catálogos',
    detalles: 'Creación de catálogo "Modalidad de Compra" con 4 elementos.',
    registroId: 'cat-modalidades',
    ip: '10.150.2.45'
  }
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-001',
    tipo: 'urgente',
    titulo: 'Vencimiento de Recepción de Ofertas',
    mensaje: 'El evento NOG 22194837 (Fibra Óptica Interinstitucional) cierra recepción de ofertas el 20 de marzo.',
    fecha: '2026-09-03T12:00:00Z',
    leida: false,
    enlaceId: 'pur-2026-004',
    categoria: 'vencimiento_oferta'
  },
  {
    id: 'notif-002',
    tipo: 'exito',
    titulo: 'Evento Adjudicado',
    mensaje: 'El evento NOG 21948201 (Servidores de Alta Disponibilidad) fue Adjudicado con dictamen GIT favorable.',
    fecha: '2026-09-02T16:15:00Z',
    leida: false,
    enlaceId: 'pur-2026-001',
    categoria: 'cambio_estatus'
  },
  {
    id: 'notif-003',
    tipo: 'alerta',
    titulo: 'Evento Declarado Desierto',
    mensaje: 'El evento NOG 21682910 (Audio/Video Salas de Juicio) fue declarado Desierto. Requiere dictamen para nueva convocatoria.',
    fecha: '2026-09-01T10:30:00Z',
    leida: true,
    enlaceId: 'pur-2026-006',
    categoria: 'cambio_estatus'
  },
  {
    id: 'notif-004',
    tipo: 'info',
    titulo: 'Nueva Solicitud Registrada',
    mensaje: 'Se ha registrado la solicitud F56-e: F56-2024-072 para Firma Electrónica Avanzada por Q.310,000.00.',
    fecha: '2026-08-30T14:20:00Z',
    leida: true,
    enlaceId: 'pur-2026-008',
    categoria: 'nuevo_registro'
  }
];
